apiVersion: v1
kind: Pod
metadata:
  name: edc-curl
spec:
  containers:
    - name: edc-curl
      image: radial/busyboxplus:curl
      command: ["/bin/sh", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "50m"
